# Generated by Django 5.2.3 on 2025-06-18 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyLogin',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'FacultyLogin',
            },
        ),
        migrations.CreateModel(
            name='FacultyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('CSE', 'Computer Science & Engineering'), ('ECE', 'Electronics & Communication Engineering'), ('ME', 'Mechanical Engineering'), ('Maths', 'Mathematics & Computing'), ('PH', 'Physics'), ('CH', 'Chemistry'), ('CE', 'Civil Engineering')], max_length=50)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('office_number', models.CharField(blank=True, max_length=15, null=True)),
                ('personal_page', models.URLField(blank=True, default='Under Construction', null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='faculty_photos/')),
                ('about_me', models.TextField(blank=True, null=True)),
                ('research_interest', models.TextField(blank=True, null=True)),
                ('cv_upload', models.FileField(blank=True, null=True, upload_to='faculty_cvs/')),
                ('publications_upload', models.FileField(blank=True, null=True, upload_to='faculty_publications/')),
                ('login', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='sharedmodels.facultylogin')),
            ],
            options={
                'db_table': 'FacultyProfile',
            },
        ),
        migrations.CreateModel(
            name='AwardHonor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name of the Award')),
                ('agency', models.CharField(max_length=255, verbose_name='Awarding Agency')),
                ('year', models.PositiveIntegerField()),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='sharedmodels.facultyprofile')),
            ],
            options={
                'db_table': 'AwardHonor',
            },
        ),
        migrations.CreateModel(
            name='Academics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=200)),
                ('year', models.PositiveIntegerField()),
                ('specialization', models.CharField(blank=True, max_length=150, null=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academics', to='sharedmodels.facultyprofile')),
            ],
            options={
                'db_table': 'Academics',
            },
        ),
        migrations.CreateModel(
            name='Guidance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=150)),
                ('program', models.CharField(choices=[('PhD', 'Ph.D.'), ('MTech', 'M.Tech'), ('BTech', 'B.Tech'), ('MSc', 'M.Sc'), ('Intern', 'Internship'), ('Other', 'Other')], max_length=20)),
                ('thesis_title', models.CharField(blank=True, max_length=300, null=True)),
                ('start_year', models.PositiveIntegerField()),
                ('end_year', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed')], max_length=20)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guidances', to='sharedmodels.facultyprofile')),
            ],
            options={
                'db_table': 'Guidance(',
            },
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=200)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.CharField(blank=True, help_text='e.g. april 2020 - Present', max_length=100, null=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='sharedmodels.facultyprofile')),
            ],
            options={
                'db_table': 'Positions',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('sponsor', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='sharedmodels.facultyprofile')),
            ],
            options={
                'db_table': 'Project',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('publication_type', models.CharField(max_length=20)),
                ('authors', models.TextField()),
                ('publication_source', models.CharField(blank=True, max_length=200, null=True)),
                ('year', models.PositiveIntegerField()),
                ('volume', models.CharField(blank=True, max_length=50, null=True)),
                ('pages', models.CharField(blank=True, max_length=50, null=True)),
                ('doi', models.CharField(blank=True, max_length=100, null=True)),
                ('impact_factor', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='sharedmodels.facultyprofile')),
            ],
            options={
                'db_table': 'Publication',
            },
        ),
        migrations.CreateModel(
            name='Teaching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=200)),
                ('course_code', models.CharField(blank=True, max_length=50, null=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachings', to='sharedmodels.facultyprofile')),
            ],
            options={
                'db_table': 'Teaching',
            },
        ),
    ]
