# Generated by Django 5.2.3 on 2025-06-18 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharedmodels', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='guidance',
            table='Guidance',
        ),
    ]
