# Generated by Django 5.2.3 on 2025-06-20 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharedmodels', '0003_remove_facultyprofile_personal_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='doi',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='impact_factor',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='pages',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='publication_source',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='publication_type',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='volume',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='year',
        ),
    ]
