# Generated by Django 5.2.3 on 2025-06-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedmodels', '0004_remove_publication_authors_remove_publication_doi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academics',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='academics',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='academics',
            name='year',
        ),
        migrations.RemoveField(
            model_name='awardhonor',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='awardhonor',
            name='year',
        ),
        migrations.RemoveField(
            model_name='guidance',
            name='end_year',
        ),
        migrations.RemoveField(
            model_name='guidance',
            name='program',
        ),
        migrations.RemoveField(
            model_name='guidance',
            name='start_year',
        ),
        migrations.RemoveField(
            model_name='guidance',
            name='status',
        ),
        migrations.RemoveField(
            model_name='guidance',
            name='thesis_title',
        ),
        migrations.RemoveField(
            model_name='positions',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='positions',
            name='role',
        ),
        migrations.RemoveField(
            model_name='project',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='project',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='role',
        ),
        migrations.RemoveField(
            model_name='project',
            name='sponsor',
        ),
        migrations.RemoveField(
            model_name='project',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='teaching',
            name='course_code',
        ),
        migrations.AlterField(
            model_name='academics',
            name='degree',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='awardhonor',
            name='name',
            field=models.TextField(verbose_name='Name of the Award'),
        ),
        migrations.AlterField(
            model_name='guidance',
            name='student_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='positions',
            name='organization',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='teaching',
            name='course_title',
            field=models.TextField(),
        ),
    ]
