# Generated by Django 5.2.3 on 2025-06-20 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharedmodels', '0005_remove_academics_institution_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academics',
            old_name='degree',
            new_name='academics_description',
        ),
        migrations.RenameField(
            model_name='guidance',
            old_name='student_name',
            new_name='guidance_details',
        ),
        migrations.RenameField(
            model_name='positions',
            old_name='organization',
            new_name='roles',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='title',
            new_name='project_description',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='title',
            new_name='publications',
        ),
        migrations.RenameField(
            model_name='teaching',
            old_name='course_title',
            new_name='teaching_description',
        ),
    ]
